[workspace]
members = ["bindings/*", "lib", "bin"]
resolver = "3"

[workspace.package]
version = "0.3.0"
authors = ["stel <stel@national.shitposting.agency>"]
edition = "2024"
description = "Read/write to Logseq note graphs in Rust"
keywords = ["logseq", "markdown", "markdown-parser", "logseq-graph"]
homepage = "https://github.com/0xstel-contrib/alleged"
repository = "https://codeberg.org/0xstel/alleged"
readme = "README.md"
license = "0BSD"

[workspace.dependencies]
time = { version = "0.3.54", features = ["formatting", "macros", "parsing", "local-offset"] }
pyo3 = "0.29.0"
alleged-lib = { path = "lib" }
icalendar = "0.17.0"
serde = { version = "1.0.0", features = ["derive"] }

[workspace.lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
