[package]
name = "alleged-lib"
exclude = [
    "/assets/",
]
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["regex-lite"]
regex = ["dep:regex"]
regex-lite = ["dep:regex-lite"]
serde = ["dep:serde", "time/serde"]
python = ["dep:pyo3"]
icalendar = ["dep:icalendar", "dep:chrono"]
hash = ["dep:twox-hash", "dep:hex"]

[dependencies]
chrono = { version = "0.4.0", optional = true }
comrak = { version = "0.54.0", default-features = false }
hex = { version = "0.4.0", optional = true }
humantime = "2.4.0"
icalendar = { workspace = true, optional = true }
nutype = "0.7.0"
pyo3 = { workspace = true, optional = true }
regex = { version = "1.13.0", optional = true }
regex-lite = { version = "0.1.0", optional = true }
rustc-hash = "2.1.0"
serde = { workspace = true, optional = true }
thiserror = "2.0.0"
time = { workspace = true }
twox-hash = { version = "2.1.0", optional = true }
uuid = { version = "1.24.0", features = ["v4"] }
walkdir = "2.5.0"
